###This is the file of the constants that the game will use

#Screen Size
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

#Player Data
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 400
SHOT_RADIUS = 5
PLAYER_SHOT_SPEED = 500

#Asteriod Data
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS